---
# tasks file for docker compose
#- name: install docker compose--step 1
#  shell: sudo curl -L https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose

- name: create dir
  file:
    path: /opt/docker-compose
    state: directory
    mode: 0755

- name: install docker compose--step 1
  copy:
    src: files/docker-compose-linux-x86_64
    dest: /opt/docker-compose
    mode: 0755

- name: install docker compose--step 2
  shell: /usr/bin/cp -f /opt/docker-compose/docker-compose-linux-x86_64 /usr/local/bin/docker-compose

- name: install docker compose--step 3
  shell: sudo chmod +x /usr/local/bin/docker-compose

- name: install docker compose--step 4
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link

- name: install docker compose--step 5
  shell: docker-compose --version
