---
# tasks file for mysql
- include_tasks: step01_user_group.yml
- include_tasks: step02_create_dir.yml
- include_tasks: step03_mysql_file.yml
- include_tasks: step04_docker_compose.yml
- include_tasks: step05_firewall.yml